# Generated by Django 3.0.4 on 2020-04-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200418_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Asymmetry_Irregular_shape',
            new_name='Border_Edge_is_not_smooth_but_Irregular',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Border_Irregular',
            new_name='Color_is_Uneven_or_dark',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Color_Uneven',
            new_name='Diameter_is_Larger_than_size_of_pencil_eraser',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Diameter_Large',
            new_name='Mole_has_Asymmetry_and_Irregular_shape',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Evolving_Texture',
            new_name='Spot_is_changing_in_size_and_shape',
        ),
    ]
