# Generated by Django 3.0.4 on 2020-04-18 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200418_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Skin_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='patient/images/'),
            preserve_default=False,
        ),
    ]
