# Generated by Django 3.0.4 on 2020-04-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_skin_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
