# Generated by Django 3.0.4 on 2020-04-19 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
