# Generated by Django 3.0.4 on 2020-04-28 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
