# Generated by Django 3.0.4 on 2020-04-28 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
